  backend:
  name: git-gateway
  branch: main # تأكد أن هذا اسم الفرع في GitHub عندك

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "تعديل الصفحات"
    files:
      - name: "index"
        label: "الصفحة الرئيسية"
        file: "index.html"
        fields:
          - { label: "العنوان", name: "title", widget: "string" }

      - name: "page2"
        label: "الصفحة الثانية"
        file: "page2.html"
        fields:
          - { label: "العنوان", name: "title", widget: "string" }

      - name: "page3"
        label: "الصفحة الثالثة"
        file: "page3.html"
        fields:
          - { label: "العنوان", name: "title", widget: "string" }

      - name: "page4"
        label: "الصفحة الرابعة"
        file: "page4.html"
        fields:
          - { label: "العنوان", name: "title", widget: "string" }